// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwSb-G63RbS1nC_qoNEwRpwxaq-RQSo8',
    appId: '1:1010446898476:web:19fa0feec08352a6214889',
    messagingSenderId: '1010446898476',
    projectId: 'talent-management-center-d0b35',
    authDomain: 'talent-management-center-d0b35.firebaseapp.com',
    databaseURL: 'https://talent-management-center-d0b35-default-rtdb.firebaseio.com',
    storageBucket: 'talent-management-center-d0b35.appspot.com',
    measurementId: 'G-3070MP3WCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7bmvGO6ZreWUFfhQVZLmpyVz-8hLgVpc',
    appId: '1:1010446898476:android:d5b8f94419d340a4214889',
    messagingSenderId: '1010446898476',
    projectId: 'talent-management-center-d0b35',
    databaseURL: 'https://talent-management-center-d0b35-default-rtdb.firebaseio.com',
    storageBucket: 'talent-management-center-d0b35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbJpd7lRXQUXM5YOlIT1QYiw8faE5JicY',
    appId: '1:1010446898476:ios:0e118fff238fe6c3214889',
    messagingSenderId: '1010446898476',
    projectId: 'talent-management-center-d0b35',
    databaseURL: 'https://talent-management-center-d0b35-default-rtdb.firebaseio.com',
    storageBucket: 'talent-management-center-d0b35.appspot.com',
    androidClientId: '1010446898476-krcrhbi19gra5u249m7lucl09hu28u4o.apps.googleusercontent.com',
    iosClientId: '1010446898476-0sbivjjtgm5a336eeht2irim8fan6u4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbJpd7lRXQUXM5YOlIT1QYiw8faE5JicY',
    appId: '1:1010446898476:ios:0e118fff238fe6c3214889',
    messagingSenderId: '1010446898476',
    projectId: 'talent-management-center-d0b35',
    databaseURL: 'https://talent-management-center-d0b35-default-rtdb.firebaseio.com',
    storageBucket: 'talent-management-center-d0b35.appspot.com',
    androidClientId: '1010446898476-krcrhbi19gra5u249m7lucl09hu28u4o.apps.googleusercontent.com',
    iosClientId: '1010446898476-0sbivjjtgm5a336eeht2irim8fan6u4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmc',
  );
}
